global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'zest-app'
    static_configs:
      - targets: ['app:8000']
    metrics_path: /metrics
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['prometheus-pushgateway:9091']
